>>> add_integer = __import__('0-add_integer').add_integer
>>> add_integer(3,4)
7
>>> add_integer(3.1, 4.9)
7
>>> add_integer(None, 2)
Traceback (most recent call last):
...
TypeError: a must be an integer
>>> add_integer(1, None)
Traceback (most recent call last):
...
TypeError: b must be an integer
>>> add_integer(6,'pythoniscool')
Traceback (most recent call last):
...
TypeError: b must be an integer
>>> add_integer('pythoniscool', 6)
Traceback (most recent call last):
...
TypeError: a must be an integer
>>> add_integer('pythoniscool', 'testingisfun')
Traceback (most recent call last):
...
TypeError: a must be an integer
>>> add_integer(5, -5)
0
>>> add_integer(100.9, -1)
99
>>> add_integer(True, 2)
Traceback (most recent call last):
...
TypeError: a must be an integer
>>> add_integer(2, False)
Traceback (most recent call last):
...
TypeError: b must be an integer
>>> add_integer(-float("inf"), 1)
Traceback (most recent call last):
...
OverflowError: cannot convert float infinity to integer
    >>> module_documentation = __import__("0-add_integer").__doc__
    >>> print(len(module_documentation) > 0)
    True

    >>> function_documentation = __import__("0-add_integer").add_integer.__doc__
    >>> print(len(function_documentation) > 0)
    True

Correct Usage:

    >>> print(add_integer(1, 2))
    3

    >>> print(add_integer(100, -2))
    98

    >>> print(add_integer(100.3, -2))
    98

    >>> print(add_integer(-100.3, -2))
    -102

    >>> print(add_integer(2**3, -2))
    6

    >>> print(add_integer(8**0.3, -2))
    -1


On Errors:
    >>> print(add_integer(4, "School"))
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> print(add_integer("Holberton", "School"))
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> print(add_integer(None, 3))
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> print(add_integer([1, 2, 3], 3))
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> print(add_integer(foo(3), -2))
    Traceback (most recent call last):
    NameError: name 'foo' is not defined
